### ISSUE TITLE
target="_blank"

### ISSUE THREAD

**Issue by arasmussen** [tasti/react-linkify#1]
Is there some way I can tell react-linkify to create links that open in new tabs?

```jsx
<Linkify target="_blank" />
```
or
```jsx
<Linkify newTab={true} />
```

**Comment by arasmussen** [comment]
I now see I can do this through the "properties" prop. Feel free to close, but consider adding this to your documentation or examples? :)

**Comment by tasti** [comment]
Yes that's right. I'll make it more clear in the documentation. Thanks!

**Comment by patrickwang717** [comment]
are there examples for this?

**Comment by main-uddin** [comment]
I used (properties, newTab,  and target ) to open link in new tab but i doesn't work, so what should i do ?

**Comment by spnintech** [comment]
```javascript
import Linkify from 'react-linkify';

<Linkify properties={{ target: '_blank' }}>
  https://github.com/
</Linkify>
```
It doesn't work with v1.0.0-alpha, but works fine with v0.2.2.

**Comment by niftytushar** [comment]
+1 You're right @ishizukih It is not working with v1.0.0-alpha

**Comment by tasti** [comment]
Does https://github.com/tasti/react-linkify/pull/51#issuecomment-355787057 answer your question?

The current docs do not currently reflect the `v1.0.0` API.

**Comment by niftytushar** [comment]
Yes, it definitely does. Thanks @tasti 
However, it would be great to update the docs.

**Comment by pvbgsharma-wal** [comment]
`<Linkify options={{target:'blank'}}> {data} </Linkify>
`this is helpful and working fine
