### ISSUE TITLE
How to convert twitter @mentions?

### ISSUE THREAD

**Issue by rajaraodv** [tasti/react-linkify#10]
I have text: 
This is some twitter text by @raja @rao bla bla 

I need to convert @raja and @rao as <a href="https://twitter.com/raja">@raja</a>  and <a href="https://twitter.com/rao">@rao</a>

Thanks!

**Comment by Nurishka** [comment]
react-linkify depends on [linkify-it](https://github.com/markdown-it/linkify-it), which provides an example for handling twitter mentions:
``` javascript
linkify.add('@', {
  validate: function (text, pos, self) {
    var tail = text.slice(pos);

    if (!self.re.twitter) {
      self.re.twitter =  new RegExp(
        '^([a-zA-Z0-9_]){1,15}(?!_)(?=$|' + self.re.src_ZPCc + ')'
      );
    }
    if (self.re.twitter.test(tail)) {
      // Linkifier allows punctuation chars before prefix,
      // but we additionally disable `@` ("@@mention" is invalid)
      if (pos >= 2 && tail[pos - 2] === '@') {
        return false;
      }
      return tail.match(self.re.twitter)[0].length;
    }
    return 0;
  },
  normalize: function (match) {
    match.url = 'https://twitter.com/' + match.url.replace(/^@/, '');
  }
});
```

You can fork react-linkify and add the code above to [line 7 in Linkify.jsx](https://github.com/tasti/react-linkify/blob/master/src/Linkify.jsx#L7)

**Comment by tasti** [comment]
You can probably add a prop to `Linkify` that takes a set of rules that follows the (schema, definition) format from https://github.com/markdown-it/linkify-it#addschema-definition. Then in the constructor, call `linkify.add(...)`.

Feel free to submit a PR.

**Comment by contra** [comment]
Would be easiest if this module exported its linkify instance, then you could do something like:


`thisModule.linkify.add('@', contentsOfPreviousComment)`

**Comment by ivanalejandro0** [comment]
I agree with the "exposing the linkify instance" approach... I've handled it on #28

**Comment by timothyallan** [comment]
Any chance of getting that commit pushed as a new NPM version? 👍

**Comment by tasti** [comment]
@timothyallan - do you mean #20? I'm planning to get related parts cleaned up for #24 very soon.

**Comment by timothyallan** [comment]
@tasti  nope, #28 The latest NPM release says that's the only commit that's missing!

**Comment by tasti** [comment]
Sorry for the delay. There's a new release to support this now!
