### ISSUE TITLE
Dollar value in link href breaks

### ISSUE THREAD

**Issue by jeffandersen** [tasti/react-linkify#2]
> Some text that is wrapped in linkify with $10.00 in it

Will display:

> 10.00in itSome text that is wrapped in linkify with $

But when copied/pasted, it is the correct value.

**Comment by bradbumbalough** [comment]
I'm having a similar issue... it's not that it's moving the dollar sign around but trying to convert the dollar amount into an IP link.

**Comment by bradbumbalough** [comment]
I was able to fix this by upgrading the package to the most recent version (`0.1.1`). I think somewhere in between is when they switched to using `linkify-it` so it handles a lot of these issues out of the box.

**Comment by tasti** [comment]
Thanks @bradbumbalough for confirming that it works now!
