### ISSUE TITLE
Hide scheme from anchor text?

### ISSUE THREAD

**Issue by olalonde** [tasti/react-linkify#22]
Would be nice to be able to hide http(s):// from the rendered link. e.g.:

Original:

```
<Linkify hideScheme>Go to https://www.github.com</Linkify>
```

Would render to:

```
Go to <a href="https://www.github.com">www.github.com</a>
```

**Comment by peterbe** [comment]
Perhaps we should re-phrase this issue, or file a new one?

In my use case I want to do something like this:
```jsx
<Linkify textRender={text => new URL(text).hostname}>Go to https://www.github.com</Linkify>
```
so you get this output:
```
Go to <a href="https://www.github.com">www.github.com</a>
```

That's just one example, but the idea that I can manipulate the text before it gets [inserted](https://github.com/tasti/react-linkify/blob/c0162319daac9e6cf9c7e8c2bcee7a5c37c9b866/src/Linkify.jsx#L61).

**Comment by Dzhakhar** [comment]
https://github.com/tasti/react-linkify/pull/36
What do you think about this commit? There is exactly what you're looking for

**Comment by tasti** [comment]
See https://github.com/tasti/react-linkify/pull/36#issuecomment-355788463.
