### ISSUE TITLE
Release is outdated

### ISSUE THREAD

**Issue by liam-onepage** [tasti/react-linkify#23]
Hi guys,

I love the library and recently included it in a project. But I noticed that the [issue regarding](https://github.com/tasti/react-linkify/issues/8) use of `for..of` is fixed yet still present in the npm version as your last release was Nov 2015. I'm using git instead of npm for now, but to help newcomers, could you please release a new version containing all recent fixes?

Thanks
-Liam

**Comment by tasti** [comment]
I've published the changes as v0.1.2. Let us know how that went.
