### ISSUE TITLE
Add common js support

### ISSUE THREAD

**Issue by vojtatranta** [tasti/react-linkify#26]
`react-linkify` is great but.

We do not use babel nor ES2015 so far and it seems that after update to `0.1.2` `react-linkify` broke our app because it uses ES2015 exports so if you require it in eg. `coffee-script`.

you get:
```
Linkify = require('react-linkify') // {default: Linkfy, ...}
```
See the problem?

Please add support for `common js` into your build process, don't rely just on ES2015 exports, thanks!

**Comment by vojtatranta** [comment]
Ooooo I know what was wrong:
this commit: https://github.com/tasti/react-linkify/commit/667b97260b18f8592105a295bfa7e66dc6fb5393

Ruined it all! I would rather use some pre release hook in the NPM, rather than manually updating stuff in git.

**Comment by tasti** [comment]
Sorry you ran into that, hoping to avoid confusion in #18 😄

**Comment by vojtatranta** [comment]
@tasti oohhh thank yooouu so much :-*
