### ISSUE TITLE
react-linkify with dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by killmenot** [tasti/react-linkify#27]
Hi folks,

is it possible to use react-linkify with dangerouslySetInnerHTML?

```
<p dangerouslySetInnerHTML={{__html: description}} /><p/>
```

**Comment by killmenot** [comment]
Nevermind, found a solution

```
const linkify = (text) => ReactDOMServer.renderToStaticMarkup(<Linkify>{text}</Linkify>)
...
<p dangerouslySetInnerHTML={{__html: linkify(description)}} /><p/>
```

Works in my case

**Comment by jvallarvisp** [comment]
The solution didn't work in my case. Please check

**Comment by marina-milicevic** [comment]
The solution didn't work in my case too.

**Comment by Colmea** [comment]
Anyone got a solution for this ? 
I'm looking for an easy (even ugly) workaround .

**Comment by killmenot** [comment]
@Colmea We decided to use https://github.com/SoapBox/linkifyjs

```js
'use strict'

import linkifyHtml from 'linkifyjs/html'

const Description = props => {
  return <div className="text">
    <p dangerouslySetInnerHTML={{__html: linkifyHtml(props.description)}} />
  </div>
}

```

**Comment by Colmea** [comment]
Thanks @killmenot , works perfectly.

Sorry for the message on Twitter. You know, deadlines... :D
