### ISSUE TITLE
how to linkify a file link?

### ISSUE THREAD

**Issue by barbalex** [tasti/react-linkify#31]
I want to wrap something like this:

    D:\Dropbox\Gabriel Software\projekte\awel-kapla\2016 03 04 Offerte\Offerte.pdf

I tried this:

    <Linkify
      properties={{
        target: '_blank',
      }}
    >
      {link.url}
    </Linkify>

but it does not build a link.

**Comment by barbalex** [comment]
Never mind: I'm working with electron. And could use this:

    import { shell } from 'electron'

and:

    <a
      href={link.url}
      onClick={(event) => {
        event.preventDefault()
        shell.openItem(link.url)
      }}
    >
      {link.url}
    </a>

**Comment by tasti** [comment]
You may also try to use the [file protocol](https://en.wikipedia.org/wiki/File_URI_scheme), `file:///`.

For example:

```
file:///D:/Dropbox/Gabriel Software/projekte/awel-kapla/2016 03 04 Offerte/Offerte.pdf
```

**Comment by barbalex** [comment]
thanks!
