### ISSUE TITLE
Global Linkify instance not available in npm version or dist/

### ISSUE THREAD

**Issue by mgoldberg524** [tasti/react-linkify#33]
Hi,

Thanks for your work on this package.

In the documentation, it is described how the global Linkify instance is made available for further customization.  I see that the feature was added in Linkify.jsx on the master branch but not in the transpiled version in dist/ which package.json points to and also not in the version on npm.

Would it be possible to build with the new changes and publish an updated version to npm to match the capabilities described in the readme? Or even to just push an updated version in dist/?

**Comment by timothyallan** [comment]
I've asked for this as well, there's a bit more info in #10
