### ISSUE TITLE
handle asia language not right

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [tasti/react-linkify#34]
I found handle `asia` language not right, eg:
```
链接http://t.cn/RcPQ214
```
I check source and found use module `linkify-it` to handle `text`, I use linkify-it's [demo](http://markdown-it.github.io/linkify-it/) and found not right parse

**Comment by tasti** [comment]
@feifeiiiiiiiiiii - Can you see if this can be resolved through [linkify-it](https://github.com/markdown-it/linkify-it)?

Additionally, you'll have the flexibility to support this on your own in `v1.0.0`. For example:
```js
const matchDecorator = (text) => {
  // Implement your matching logic here to support 链接http://t.cn/RcPQ214
};

<Linkify matchDecorator={matchDecorator}>
  ...
</Linkify>
```

`matchDecorator` lets you override the default linkify-it logic to match URLs however you'd like.

Any feedback is appreciated.
