### ISSUE TITLE
Calling PropTypes validators directly is not supported by the `prop-types` package.

### ISSUE THREAD

**Issue by robertftw** [tasti/react-linkify#39]
Gertting this error in console with Linkify:

> Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types Check the render method of `Readmore`.

My code:
`  <div className="col-12 col-9-tablet col-8-hd center-element no-padding">
                        <Linkify properties={{target: '_blank'}}>
                            <p>{'Lorem ipsum dolor sit amet, postea scripta accusam in vel, duo at eros simul appareat, nam ei accusam adipisci reformidans. Duo fabulas moderatius contentiones in, cu vis duis oportere. Eum paulo assentior et. Semper integre ei quo, ius et semper vidisse tibique.Dicta perpetua gloriatur has et, te nostro electram efficiantur eum. Ius minim causae honestatis an, nam id vide duis probo, congue libris cu eos. No usu habeo forensibus, at nam evertitur torquatos. Moderatius accommodare ad nec. Essent apeirian eu vix, ne everti civibus salutatus vix. Ea eros ferri est, sit aliquando contentiones cu. http://google.com'}</p>
                        </Linkify>
                    </div>`

However it works but the console error is annoying.

**Comment by pablolmiranda** [comment]
Could you please provide a github repo that reproduces the issue?

**Comment by ledhed2222** [comment]
same here - react 0.14.3 and linkify 0.2.1. will try to reproduce when i have a second

**Comment by pablolmiranda** [comment]
You can try to use codesandbox.io if it helps

**Comment by ledhed2222** [comment]
Guau, qué herramienta impresionante Pablo!

Anyway yes, I could easily recreate this. I thought it might have had to do with using the `properties` prop of `Linkify` but it doesn't seem so.

https://codesandbox.io/s/66x8qk4ER?module=%2FHello.js

**Comment by robertftw** [comment]
@pablolmiranda https://stackblitz.com/edit/react-ebfaso

**Comment by pablolmiranda** [comment]
@ledhed2222 @robertftw, found the issue.
The problem here is the prop-types module is not build to work with a React <= 15.5.0.
To not see this error anymore you need to update your React to version >= 15.5.0.

**Comment by tasti** [comment]
Solution provided above, but in addition, `prop-types` will no longer be used in favor of flowtype in `v1.0.0`.
