### ISSUE TITLE
Use external library for link detection/parsing

### ISSUE THREAD

**Issue by danez** [tasti/react-linkify#4]
Hey, I really like this component, it is simple and instantly worked.

One thing that bugs me is that you are doing the detection of links on your own inside the component.
Wouldn't it be better to use some bulletproof library to do this job? So the only thing the component needs to care then is creating the elements.

There is for example this library https://github.com/markdown-it/linkify-it which is heavily used (nearly 200k downloads on npm). 

If you are interested I could create a pull request for this. What do you think?

**Comment by tasti** [comment]
This sounds like an interesting idea. I was worried about the current regex that I'm using, and this seems like a more rigorous alternative.

Go ahead with a pull request and we'll take it from there.
