### ISSUE TITLE
Add hook that allows customization of link text

### ISSUE THREAD

**Issue by dpup** [tasti/react-linkify#40]
URLs can be long and not very human readable. It would be nice to have an option where-by the link text can be customized, either by extracting context from the URL or making a background request to fetch metadata.

    https://www.google.ru/maps/@59.9393895,30.3165389,15z
    --> <a href="https://www.google.ru/maps/@59.9393895,30.3165389,15z">Map (59.9393895N 30.3165389E)</a>

    https://www.google.com/maps/place/New+York,+NY
    --> <a href="https://www.google.com/maps/place/New+York,+NY">New York, NY</a>

Usage could be something like:

    <Linkify tranform={fn}>{text}</Linkify>

**Comment by yarnball** [comment]
+1 on this.

For example, it could do a fetch of the link, then return the page title. I'm trying this here- https://codesandbox.io/s/9rjD5X9xz

**Comment by pablolmiranda** [comment]
It should be ok to add a hook, `tansformAnchorText`, where you can receive the text before create the anchor element

**Comment by tasti** [comment]
See https://github.com/tasti/react-linkify/pull/46#issuecomment-355787477.
