### ISSUE TITLE
String not recognized

### ISSUE THREAD

**Issue by infojunkie** [tasti/react-linkify#41]
The following string `iTunes:bit.ly/oaKTSQ` does not get linkified whereas `iTunes: bit.ly/oaKTSQ` does. It's a bit ambiguous of course, but do you suggest any option to support it?

**Comment by pablolmiranda** [comment]
if you add a protocol prefix it should work just fine: `http://bit.ly/oaKTSQ` or `https://bit.ly/oaKTSQ`

**Comment by infojunkie** [comment]
Thanks, but I don't control the strings to be linkified - I get them from user input.

**Comment by pablolmiranda** [comment]
@infojunkie, the domains without a scheme are detected using [node-tlds](https://github.com/stephenmathieson/node-tlds).
bit.ly doesn't match any TLDs on that list, that's why we don't detect it as a valid URL.
Could you parse the user input and add the scheme to the bit.ly URLs ?
```
const text = userInput.replace(/(bit.ly\/\w+)/g, 'http://$1')
```

**Comment by infojunkie** [comment]
I see, thanks. since `ly` is a valid TLD, it should probably be supported by `node-tlds`. I will ask them to refresh the list because the source list at IANA has been updated and does include `ly`.

**Comment by infojunkie** [comment]
Thanks. The latest `node-tlds` release (1.194.0) does include the TLD `ly` at https://github.com/stephenmathieson/node-tlds/blob/master/index.js#L772. So it's just a matter of updating the module version in your deps?

**Comment by infojunkie** [comment]
Sorry but I don't think I understand your explanation:
- I checked that my version of `node-tlds` is 1.192.0 which already includes the tld `ly`
- Notice how `bit.ly/oaKTSQ` is actually recognized provided there's a space before the `:` colon

**Comment by pablolmiranda** [comment]
Ok, I got it.
The scheme Itunes:bit.ly doesn't qualify as a valid schema and [linkify-it](https://github.com/markdown-it/linkify-it) module doesn't understand  it.
If you use itunes://bit.ly/1234, this will be possible to support since it could be a valid URL schema. But for my understanding, this will not trigger the desired behavior on your side.
I will suggest to you open an issue for [linkify-it](https://github.com/markdown-it/linkify-it) asking how they can support the URL schema you need.

**Comment by tasti** [comment]
@infojunkie - As mentioned above, you should see if this can be resolved through [linkify-it](https://github.com/markdown-it/linkify-it).

Additionally, you'll have the flexibility to support this on your own in `v1.0.0`. For example:
```js
const matchDecorator = (text) => {
  // Implement your matching logic here to support iTunes:bit.ly/oaKTSQ
};

<Linkify matchDecorator={matchDecorator}>
  ...
</Linkify>
```

`matchDecorator` lets you override the default linkify-it logic to match URLs however you'd like.

Any feedback is appreciated.
