### ISSUE TITLE
Suggestion: add option to set text using property dangerouslySetInnerHTML.

### ISSUE THREAD

**Issue by oztek22** [tasti/react-linkify#49]
In render of Linkify.jsx, you can replace return code with this line to add supports to HTML tags.
`<span className={this.props.className}  dangerouslySetInnerHTML={{ __html: parsedChildren }}></span>`

**Comment by tasti** [comment]
Support for `dangerouslySetInnerHTML` was intentionally left out since it's, you know, dangerous.

If you have text that contains HTML tags that you also want to linkify, you can do so by first running it through `dangerouslySetInnerHTML`, and then using `Linkify` on the result. For example:
```
<Linkify>
  <span dangerouslySetInnerHTML={{__html: text}}></span>
</Linkify>
```

**Comment by BrodaNoel** [comment]
@tasti not sure why, but that actually doesn't work.

I have this:
```jsx
<Linkify>
  <p className="col-md-7" dangerouslySetInnerHTML={{ __html: description }} />
</Linkify>
```

And it renders:
```html
<span class="Linkify">
  <p class="col-md-7">
    <p>blablabla https://google.com google.com asdasd</p>
  </p>
</span>
```

The content of `decription` is: `<p>blablabla https://google.com google.com asdasd</p>`

**Comment by ricardosouza-logmein** [comment]
this issue should not be closed, this ticket still valid IMO
