### ISSUE TITLE
Avoid <span class="Linkify"> wrapper

### ISSUE THREAD

**Issue by ibc** [tasti/react-linkify#50]
Starting from React 16 there is no need for a component to wrap all its content into a single HTML tag, so `react-linkify` could just keep the original elements by just replacing links with `<a>` tags.

**Comment by tasti** [comment]
Keep an eye out for the above PR, which uses `React.Fragment` instead of wrapping everything in a `span` as you mentioned.

**Comment by shanecav84** [comment]
@tasti Can we get a release with the `React.Fragment` functionality?
