### ISSUE TITLE
Accept HTML markup for links first, then parse URLs

### ISSUE THREAD

**Issue by MaffooBristol** [tasti/react-linkify#60]
Hi, thanks for the module. Unfortunately it doesn't do what I was expecting, so I won't be using it right now. But one suggestion I have is to also parse actual HTML for links. For example:

![image](https://user-images.githubusercontent.com/3296828/38635718-1eb5f9d8-3dbe-11e8-8efd-9e24db579120.png)

I know I can just change the way the content of the variable is printed and use dangerouslySetInnerHtml or whatever it's named, but I don't really want to... dangerously set inner HTML. I only want it to run for links, which is why a quick google brought up this module.

Would it be possible to attempt to convert the `<a href="http://www.google.com">Google</a>` instances first and then, if failing to find them, convert the actual link inside? Otherwise you get the weird bug seen above.

Thanks
Matt

**Comment by tasti** [comment]
The screenshot you shared is the expected (default) behavior.

What you're doing seems to be best solved using `dangerouslySetInnerHTML`, as you suggested. We don't intend this library to be a full-fledged html parser, which is what it'd take to solve the scenario you've described.

However, you can write a custom `matchDecorator` (follow https://github.com/tasti/react-linkify/blob/master/src/decorators/defaultMatchDecorator.js) to implement your own parser. This is probably the way to go.

I'll close this issue, but if you need more guidance feel free to re-open.

**Comment by MaffooBristol** [comment]
Thanks. I just went for a different route and I entirely understand that you don't want to bloat the module with extra stuff like that. Cheers for getting back to me on it though!
