### ISSUE TITLE
Latest Dist is not latest build

### ISSUE THREAD

**Issue by iwnnay** [tasti/react-linkify#70]
I should have been able to use my own componentDecorator but the replacement "component" is not used in a way that is extensible. In the src it seems to be fine. Just needs another build from what I can tell.

**Comment by ian** [comment]
I can confirm this is an issue.  Was trying to use the decorator props and they're not present.  The release only has one file, `Linkify.jsx`

![Screen Shot 2019-05-28 at 5 23 53 PM](https://user-images.githubusercontent.com/19853/58516452-99026480-816d-11e9-887e-2654231fd4ed.png)

**Comment by tasti** [comment]
Published `v1.0.0-alpha` 🎉

https://www.npmjs.com/package/react-linkify/v/1.0.0-alpha
