### ISSUE TITLE
Readme and example site is outdated

### ISSUE THREAD

**Issue by dannystyleart** [tasti/react-linkify#79]
Documentation and last npm published version has a whole lot API breaking changes, and therefore both the readme and examples site is useless.

Tried to use this component, and did not understand why nothing works a according to the docs.
Checked the package in node_modules and there were a total different API.

Please update both the examples and the docs.

**Comment by kpietkaa** [comment]
Before the readme update learn from here. 
Works: `"^1.0.0-alpha"`
```js
const componentDecorator = (href, text, key) => (
  <a
    href={href}
    key={key}
    target="_blank"
    style={{ textDecoration: 'underline' }}
  >
    {text}
  </a>
);

<Linkify componentDecorator={componentDecorator}>
  ...
</Linkify>
```

**Comment by dannystyleart** [comment]
Thanks,
Now it's fine.

Closing
